replicaCount: 1

image:
  repository: bitnami/nginx
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

containerPorts:
  http: 8080

ingress:
  enabled: true
  ingressClassName: alb
  hostname: "www.sdlc.aws.cockydevops.com"  # Ignored if rules provided
  annotations:
    alb.ingress.kubernetes.io/load-balancer-name: shared
    alb.ingress.kubernetes.io/group.name: shared
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443},{"HTTP":80}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:975705621738:certificate/b23a3ab3-c7f1-4868-a975-8b865fcc6420
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS13-1-2-Res-2021-06
  rules:
    - host: www.sdlc.aws.cockydevops.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-welcome
                port:
                  number: 8080
  extraHosts:
   - name: www.cockydevops.com
     path: /    

html:
  index: |
    <html>
      <head><title>Welcome</title></head>
      <body><h1>Welcome to Nginx!</h1></body>
    </html>