apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: sdlc-dev-failover-blue
  region: us-east-1
  version: "1.31"

vpc:
  id: vpc-0393e1a05766d6cea
  subnets:
    private:
      private-one: { id: subnet-00251a1358bc64917 }
      private-two: { id: subnet-06b39a3293aae56a7 }

managedNodeGroups:
  - name: general
    instanceType: t3a.medium
    minSize: 3
    desiredCapacity: 3
    privateNetworking: true

nodeGroups:
  - name: cluster-services
    labels:
      role: &clusterServices cluster-services
    taints:
      - key: *clusterServices
        value: "true"
        effect: "NoSchedule"
    instanceType: t3a.medium
    minSize: 3
    desiredCapacity: 3
    privateNetworking: true
    iam:
      withAddonPolicies:
        appMesh: true
        appMeshPreview: true
        autoScaler: true
        awsLoadBalancerController: true
        certManager: true
        cloudWatch: true
        ebs: true
        efs: true
        externalDNS: true
        fsx: true
        imageBuilder: true
        xRay: true
