apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: &clusterName sdlc-dev-blue
  region: us-west-2
  version: "1.31"

iam:
  podIdentityAssociations:
    - namespace: kube-system
      serviceAccountName: cluster-autoscaler
      roleName: cluster-autoscaler
      wellKnownPolicies:
        autoScaler: true

vpc:
  id: vpc-id
  subnets:
    private:
      private-one: { id: subnet-id }
      private-two: { id: subnet-id }

addonsConfig:
  disableDefaultAddons: true
  autoApplyPodIdentityAssociations: true
addons:
  - name: aws-ebs-csi-driver
    version: "1.35.0"
    useDefaultPodIdentityAssociations: true
    configurationValues: |
      controller:
        replicaCount: 2
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    app: ebs-csi-controller
                topologyKey: "kubernetes.io/zone"
          nodeAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                preference:
                  matchExpressions:
                    - key: role
                      operator: In
                      values:
                        - cluster-services
        tolerations:
          - operator: "Exists"
            effect: "NoSchedule"
      node:
        tolerateAllTaints: true

  - name: coredns
    version: "1.11.3"
    useDefaultPodIdentityAssociations: true
    configurationValues: |
      replicaCount: 2
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  eks.amazonaws.com/component: coredns
              topologyKey: "kubernetes.io/zone"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - cluster-services
      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"

  - name: eks-pod-identity-agent
    version: "1.3.2"
    useDefaultPodIdentityAssociations: true
    configurationValues: |
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app.kubernetes.io/name: eks-pod-identity-agent
              topologyKey: "kubernetes.io/zone"
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              preference:
                matchExpressions:
                  - key: role
                    operator: In
                    values:
                      - cluster-services
      tolerations:
        - operator: "Exists"
          effect: "NoSchedule"

  - name: kube-proxy
    useDefaultPodIdentityAssociations: true
    version: "1.31.0"

  - name: vpc-cni
    version: "1.18.5"
    useDefaultPodIdentityAssociations: true

cloudWatch:
  clusterLogging:
    enableTypes: [ "all" ]
    logRetentionInDays: 1

managedNodeGroups:
  - name: cluster-autoscaler
    labels:
      role: &clusterAutoscaler cluster-autoscaler
    taints:
      - key: "role"
        value: *clusterAutoscaler
        effect: "NoSchedule"
    instanceType: t4g.medium
    minSize: 2
    maxSize: 10
    privateNetworking: true
    volumeSize: 20
    ebsOptimized: true

  - name: cluster-services
    labels:
      role: &clusterServices cluster-services
    taints:
      - key: "role"
        value: *clusterServices
        effect: "NoSchedule"
    instanceType: t4g.medium
    minSize: 0
    maxSize: 10
    privateNetworking: true
    volumeSize: 20
    ebsOptimized: true

  - name: general
    instanceType: t4g.medium
    minSize: 0
    maxSize: 25
    privateNetworking: true
    ebsOptimized: true
