aws-ebs-csi-driver:
  controller.region: us-west-2
  controller.nodeSelector: &cluster-services cluster-services
  enableVolumeResizing: true
  node.tolerateAllTaints: true

cluster-autoscaler:
  autoDiscovery:
    clusterName: &clusterName blue
  nodeSelector:
    role: *cluster-services
  tolerations:
    - key: "role"
      operator: "Equal"
      value: *cluster-services
      effect: "NoSchedule"
  replicaCount: 2

# aws-load-balancer-controller:
#   # Load Balancer Controller specific configurations
#   clusterName: your-cluster-name
#   region: your-region
#   vpcId: your-vpc-id
