# global:
#   tolerations:
#     - key: "role"
#       operator: "Equal"
#       value: cluster-services
#       effect: "NoSchedule"

clusterName: &clusterName "dev-blue"

# aws-ebs-csi-driver:
#   # EBS CSI Driver specific configurations
#   enableVolumeScheduling: true
#   enableVolumeResizing: true
#   enableVolumeSnapshot: true

# aws-load-balancer-controller:
#   # Load Balancer Controller specific configurations
#   clusterName: your-cluster-name
#   region: your-region
#   vpcId: your-vpc-id

cluster-autoscaler:
  autoDiscovery:
    clusterName: *clusterName
  nodeSelector:
    role: cluster-services
  tolerations:
    - key: "role"
      operator: "Equal"
      value: cluster-services
      effect: "NoSchedule"